# Generated by Django 5.2 on 2025-05-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_userwidgetconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
